[project]
name = "university-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=2.3.0",
    "langchain>=1.0.3",
    "langchain-ollama>=1.0.0",
    "langchain-tavily>=0.2.13",
]
